# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/peoples-coin-service:latest', '.']
images:
  - 'gcr.io/${PROJECT_ID}/peoples-coin-service:latest'
options:
  logging: CLOUD_LOGGING_ONLY
