steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ['build', '-t', 'gcr.io/heroic-tide-428421-q7/peoples-coin-service:$COMMIT_SHA', '.']

# 2. Push the container image to the registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ['push', 'gcr.io/heroic-tide-428421-q7/peoples-coin-service:$COMMIT_SHA']

# 3. Deploy the new image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'peoples-coin-service'
    - '--image=gcr.io/heroic-tide-428421-q7/peoples-coin-service:$COMMIT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances=heroic-tide-428421-q7:us-central1:peoples-coin-cluster-final'
    - '--set-env-vars=DATABASE_URL=postgresql+pg8000://postgres:NDfcIdlRk0@/brightacts?unix_sock$

# This section must have zero indentation
images:
- 'gcr.io/heroic-tide-428421-q7/peoples-coin-service:$COMMIT_SHA'
