steps:
  # Step 1: Build the Docker image (FORCE amd64 to match Cloud Run runtime)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform=linux/amd64', '-t', 'gcr.io/heroic-tide-428421-q7/peoples-coin-service:latest', '.']

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'peoples-coin-service',
        '--image', 'gcr.io/heroic-tide-428421-q7/peoples-coin-service:latest',
        '--region', 'us-east4',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/heroic-tide-428421-q7/peoples-coin-service:latest'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'projects/105378934751/serviceAccounts/105378934751-compute@developer.gserviceaccount.com'

