steps:
  # Step 1: Build the Docker image (amd64)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform=linux/amd64', '-t', 'gcr.io/heroic-tide-428421-q7/peoples-coin-service:latest', '.']

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/heroic-tide-428421-q7/peoples-coin-service:latest']

  # Step 3: Deploy to Cloud Run in us-central1
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'peoples-coin-service',
        '--image', 'gcr.io/heroic-tide-428421-q7/peoples-coin-service:latest',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/heroic-tide-428421-q7/peoples-coin-service:latest'

options:
  logging: CLOUD_LOGGING_ONLY

