steps:
# Step 1: Build the container image
# This step builds the Docker image from the Dockerfile in the current directory.
# The '-t' flag tags the image with the full Artifact Registry path.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/heroic-tide-428421-q7/docker-repo/peoples-coin-service:latest',
    '.'
  ]

# Step 2: Deploy to Cloud Run
# This step uses the gcloud command to deploy the image we just built.
# It pulls the image directly from the Artifact Registry path specified.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'peoples-coin-service',
    '--image', 'us-central1-docker.pkg.dev/heroic-tide-428421-q7/docker-repo/peoples-coin-service:latest',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--memory', '1Gi',
    '--cpu', '1',
    '--allow-unauthenticated'
  ]

# The 'images' key is the magic part. It tells Cloud Build to automatically
# push the image we built in Step 1 to the Artifact Registry before Step 2 runs.
images:
- 'us-central1-docker.pkg.dev/heroic-tide-428421-q7/docker-repo/peoples-coin-service:latest'

options:
  logging: CLOUD_LOGGING_ONLY

