# 3. Deploy the container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'peoples-coin-service'
    - '--image=gcr.io/heroic-tide-428421-q7/peoples-coin-service:$COMMIT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    # THIS IS THE CRITICAL NEW LINE
    - '--add-cloudsql-instances=heroic-tide-428421-q7:us-central1:peoples-coin-cluster-final'
    # YOU MUST UPDATE YOUR DATABASE_URL TO THIS FORMAT
    - '--set-env-vars=DATABASE_URL=postgresql+pg8000://postgres:NDfcIdlRk0@/brightacts?unix_socket=/cloudsql/heroic-tide-428421-q7:us-central1:peoples-coin-cluster-final'

