steps:
  # Step 1: Print working directory
  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'echo "Current Dir:" && pwd && ls -la']

  # Step 2: Set up Docker Buildx and build for linux/amd64
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker buildx create --use
        docker buildx build --platform=linux/amd64 \
          -t gcr.io/heroic-tide-428421/peoples-coin-service:latest \
          --push .

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'peoples-coin-service',
        '--image', 'gcr.io/heroic-tide-428421/peoples-coin-service:latest',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--memory', '1Gi',
        '--cpu', '1',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/heroic-tide-428421/peoples-coin-service:latest'

options:
  logging: CLOUD_LOGGING_ONLY

