"""Create user_accounts table with goodwill_coins

Revision ID: 2c14a2dde935
Revises: 
Create Date: 2025-07-23 17:47:11.305094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c14a2dde935'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_hash', sa.String(length=128), nullable=False),
    sa.Column('previous_hash', sa.String(length=128), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_hash')
    )
    op.create_table('event_logs',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_type_timestamp', 'event_logs', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('is_premium', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_by'), 'users', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('api_keys',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('council_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_council_members_deleted_by'), 'council_members', ['deleted_by'], unique=False)
    op.create_table('goodwill_actions',
    sa.Column('performer_user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contextual_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('loves_value', sa.Integer(), nullable=False),
    sa.Column('resonance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'PENDING_VERIFICATION'"), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blockchain_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['performer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blockchain_tx_hash')
    )
    op.create_index(op.f('ix_goodwill_actions_deleted_by'), 'goodwill_actions', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_goodwill_actions_performer_user_id'), 'goodwill_actions', ['performer_user_id'], unique=False)
    op.create_table('proposals',
    sa.Column('proposer_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('vote_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vote_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('required_quorum', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('proposal_type', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT', 'VOTING', 'PASSED', 'FAILED', 'EXECUTED')", name='chk_proposal_status_valid'),
    sa.ForeignKeyConstraint(['proposer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_deleted_by'), 'proposals', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_proposals_proposer_user_id'), 'proposals', ['proposer_user_id'], unique=False)
    op.create_table('user_wallets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_address', sa.String(length=42), nullable=False),
    sa.Column('blockchain_network', sa.String(length=50), server_default=sa.text("'Ethereum Mainnet'"), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_address')
    )
    op.create_index(op.f('ix_user_wallets_user_id'), 'user_wallets', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('blockchain_tx_hash', sa.String(length=66), nullable=False),
    sa.Column('goodwill_action_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('token_symbol', sa.String(length=10), server_default=sa.text("'GOODWILL'"), nullable=False),
    sa.Column('sender_address', sa.String(length=42), nullable=False),
    sa.Column('receiver_address', sa.String(length=42), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'CONFIRMED'"), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('initiator_user_id', sa.UUID(), nullable=True),
    sa.Column('receiver_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goodwill_action_id'], ['goodwill_actions.id'], ),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_block_number'), 'ledger_entries', ['block_number'], unique=False)
    op.create_index(op.f('ix_ledger_entries_blockchain_tx_hash'), 'ledger_entries', ['blockchain_tx_hash'], unique=True)
    op.create_index(op.f('ix_ledger_entries_goodwill_action_id'), 'ledger_entries', ['goodwill_action_id'], unique=True)
    op.create_index(op.f('ix_ledger_entries_initiator_user_id'), 'ledger_entries', ['initiator_user_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_receiver_user_id'), 'ledger_entries', ['receiver_user_id'], unique=False)
    op.create_table('votes',
    sa.Column('voter_user_id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('vote_value', sa.String(length=10), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['voter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_deleted_by'), 'votes', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_votes_proposal_id'), 'votes', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_votes_voter_user_id'), 'votes', ['voter_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_voter_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_proposal_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_deleted_by'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_ledger_entries_receiver_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_initiator_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_goodwill_action_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_blockchain_tx_hash'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_block_number'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_user_wallets_user_id'), table_name='user_wallets')
    op.drop_table('user_wallets')
    op.drop_index(op.f('ix_proposals_proposer_user_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_deleted_by'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_goodwill_actions_performer_user_id'), table_name='goodwill_actions')
    op.drop_index(op.f('ix_goodwill_actions_deleted_by'), table_name='goodwill_actions')
    op.drop_table('goodwill_actions')
    op.drop_index(op.f('ix_council_members_deleted_by'), table_name='council_members')
    op.drop_table('council_members')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_by'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index('idx_event_type_timestamp', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_table('chain_blocks')
    # ### end Alembic commands ###
